### ISSUE TITLE
Unable to detect dices on macOS with Chrome

### ISSUE THREAD

**Issue by HapLifeMan** [ParticulaCode/GoDiceJavaScriptAPI#1]
Hello,

I just received my GoDice package today and already started enjoying the app!

Now I'd like to dig into this package to play with the API and build awesome things.

But I'm facing an issue, when trying to connect dices, nothing is detected, can you help me?

<img width="493" alt="CleanShot 2022-05-17 at 10 26 54@2x" src="https://user-images.githubusercontent.com/1854141/168769992-fa4b64e6-ab13-4db8-9b30-aeb9d565b37f.png">

Using macOS 12.3.1 with Chrome 101.0.4951.64.

Thanks!

**Comment by HapLifeMan** [comment]
After a few hours and without touching anything, I have 4 dices connected.
On these dices, bluetooth signal is low when they're barely 5 centimeters away of my MacBook Pro.
They're losing connection after 30-40 centimeters, what's happening?

<img width="120" alt="CleanShot 2022-05-17 at 17 42 06@2x" src="https://user-images.githubusercontent.com/1854141/168852734-a33df33c-0a0d-4178-ae5c-db5fbf0df366.png">

And still impossible to have the others connected 😕

**Comment by bacrossland** [comment]
@HapLifeMan try disconnecting the dice from the device the app is on. Your Mac and that device might be fighting for control of the dice.

I just got mine now and will charge them then trying this script out later today.

**Comment by nsander** [comment]
I was facing this issue as well, but adding `Google Chrome` to allowed apps to use Bluetooth in `Security & Privacy` setting in OSX fixed this for me.

**Comment by ParticulaCode** [comment]
- Make sure the dice are not connected to any device
-  Add Google Chrome to allow apps to use Bluetooth in Security & Privacy setting in OSX
