### ISSUE TITLE
Bluetooth Range

### ISSUE THREAD

**Issue by Esshahn** [ParticulaCode/GoDiceJavaScriptAPI#13]
I'm considering buying the dice for a kids playground.
The dice would be placed inside bigger (around 60cm) foam dice.
A Rpi would read the status of the dice which would be rolled on an 3x3 meter playfield.

Do you have any experience about the bluetooth signal strength? Is this idea realistic?
Thank you very much for your consideration.

**Comment by binaryben** [comment]
Just from my anecdotal observations playing with them, I don't think it's realistic. Sometimes the dice drop out around the 1.5-2m mark for me (across my dining table if I'm hosting a game at one end). This is naked without any shells. 

Others might have more positive experiences to share though. Maybe it's possible to get better performance with a host that isn't a mobile phone? I've got some projects that I want to use a RPi brain for as well so I'm keen to see how it goes for you. 

Sounds fun!

**Comment by Esshahn** [comment]
Thank you very much for your helpful observations. That is indeed not ideal for the planned use case. I will consider other options first then. Cheers!
