### ISSUE TITLE
DnD Shells

### ISSUE THREAD

**Issue by astromediaonly** [ParticulaCode/GoDiceJavaScriptAPI#2]
Hi, can we get also example for handling dnd shells? I did not checked unity example yet but it seems there is no mention about those here (if its same there it would be nice to add it there too).

**Comment by ProfDeCube** [comment]
Yeah, currently there's only handling for the bare dice. I have some quick code that I put together to check for the 20 sided shells, Currently working on the 24 sided ones and once those are done I'll tidy up and set up a new branch.

**Comment by ParticulaCode** [comment]
DnD Shells are now supported
